# -*- coding: utf-8 -*-
"""Bubblesort.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TBAqQC3sAmhWhsZpHGTXcmCCLvMqXD3E
"""

# Implementation of Bubble sort

def bubbleSort(a):
	n = len(a)
	# optimize code, so if the array is already sorted, it doesn't need
	# to go through the entire process
	swapped = False
	# Traverse through all array elements
	for i in range(n-1):
		# range(n) also work but outer loop will
		# repeat one time more than needed.
		# Last i elements are already in place
		for j in range(0, n-i-1):

			# traverse the array from 0 to n-i-1
			# Swap if the element found is greater
			if a[j] > a[j + 1]:
				swapped = True
				a[j], a[j + 1] = a[j + 1], a[j]
		
		if not swapped:
			# if we haven't needed to make a single swap, we can just exit the main loop.
			return


a = []
n = int(input('Enter Number of Elements:'))
for i in range(n):
  a.append(int(input("Enter Elements:")))
print("Array before sorting",a)
bubbleSort(a)

print("Array After Sorting:")
for i in range(len(a)):
	print("% d" % a[i], end=" ")